import { createSystem, defaultConfig, defineConfig, type SystemStyleObject } from '@chakra-ui/react'

const config = defineConfig({
  theme: {
    tokens: {
      colors: {
        blue: { value: '#3355FF' },
        'blue-dark': { value: '#1F3ADB' },
        maroon: { value: '#8B2E3F' },
        ink: { value: '#12131A' },
        'ink-soft': { value: '#4A4B57' },
        paper: { value: '#FAFAFB' },
        mist: { value: '#EEF1FF' },
        line: { value: '#E4E6EF' },
        white: { value: '#FFFFFF' },
        orange: { value: '#BC4800' },
        muted: { value: '#6B7280' },
      },
    },
  },
  globalCss: {
    "p, li": {
      "color": "var(--chakra-colors-ink-soft)",
    },
    ".chakra-linkbox": {
      "display": "flex",
      "flexDirection": "column",
      "padding": "22px",
      "border": "1px solid var(--chakra-colors-line)",
      "borderRadius": "var(--radius-md)",
      "background": "var(--chakra-colors-white)",
      "transition": "border-color 0.2s ease, transform 0.2s ease",
    },
    ".chakra-linkbox:hover": {
      "borderColor": "var(--chakra-colors-blue)",
      "transform": "translateY(-2px)",
    },
    ".chakra-linkbox__overlay": {
      "color": "var(--chakra-colors-blue) !important",
    },
    ".chakra-linkbox:hover .chakra-linkbox__overlay": {
      "textDecoration": "underline !important",
    },
    ":root": {
      "--font-sans": "'Plus Jakarta Sans', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
      "--font-mono": "'Space Mono', monospace",
      "--container": "1200px",
      "--radius-sm": "10px",
      "--radius-md": "16px",
      "--radius-lg": "24px",
      "--shadow-card": "0 1px 2px rgba(18, 19, 26, 0.04), 0 8px 24px rgba(18, 19, 26, 0.06)",
    },
    "*": {
      "boxSizing": "border-box",
    },
    "html": {
      "scrollBehavior": "smooth",
    },
    "body": {
      "margin": "0",
      "fontFamily": "var(--font-sans)",
      "color": "var(--chakra-colors-ink)",
      "background": "var(--chakra-colors-paper)",
      "WebkitFontSmoothing": "antialiased",
    } as SystemStyleObject,
    "h1, h2, h3, h4, p, figure": {
      "margin": "0",
    },
    "img": {
      "maxWidth": "100%",
      "display": "block",
    },
    "a": {
      "color": "inherit",
      "textDecoration": "none",
    },
    ".container": {
      "maxWidth": "var(--container)",
      "margin": "0 auto",
      "padding": "0 24px",
    },
    ".site": {
      "display": "flex",
      "flexDirection": "column",
      "minHeight": "100vh",
    },
    "main": {
      "flex": "1",
    },
    ".section": {
      "padding": "96px 0",
      "@media (max-width: 720px)": {
        "padding": "64px 0",
      },
    },
    ".eyebrow": {
      "fontFamily": "var(--font-mono)",
      "fontSize": "14px",
      "fontWeight": "700",
      "letterSpacing": "1.4px",
      "textTransform": "uppercase",
      "color": "var(--chakra-colors-blue)",
      "marginBottom": "16px",
    },
    ".lede": {
      "fontSize": "19px",
      "lineHeight": "1.6",
      "color": "var(--chakra-colors-ink-soft)",
      "maxWidth": "640px",
    },
    "h1": {
      "fontSize": "clamp(38px, 6vw, 64px)",
      "fontWeight": "800",
      "lineHeight": "1.05",
      "letterSpacing": "-0.02em",
    },
    "h2": {
      "fontSize": "clamp(28px, 4vw, 42px)",
      "fontWeight": "800",
      "lineHeight": "1.1",
      "letterSpacing": "-0.01em",
    },
    "h3": {
      "fontSize": "22px",
      "fontWeight": "700",
      "lineHeight": "1.3",
    },
    ".btn": {
      "display": "inline-flex",
      "alignItems": "center",
      "gap": "8px",
      "padding": "14px 26px",
      "borderRadius": "999px",
      "fontWeight": "600",
      "fontSize": "15px",
      "border": "1px solid transparent",
      "cursor": "pointer",
      "transition": "transform 0.15s ease, background 0.15s ease, border-color 0.15s ease",
    },
    ".btn:hover": {
      "transform": "translateY(-1px)",
    },
    ".btn--primary": {
      "background": "var(--chakra-colors-blue)",
      "color": "var(--chakra-colors-white)",
    },
    ".btn--primary:hover": {
      "background": "var(--chakra-colors-blue-dark)",
    },
    ".btn--secondary": {
      "background": "transparent",
      "borderColor": "var(--chakra-colors-line)",
      "color": "var(--chakra-colors-ink)",
    },
    ".btn--secondary:hover": {
      "borderColor": "var(--chakra-colors-blue)",
      "color": "var(--chakra-colors-blue)",
    },
    ".btn--small": {
      "padding": "10px 18px",
      "fontSize": "14px",
    },
    ".btn-row": {
      "display": "flex",
      "gap": "14px",
      "flexWrap": "wrap",
      "marginTop": "36px",
    },
    ".nav": {
      "position": "sticky",
      "top": "0",
      "zIndex": "40",
      "background": "rgba(250, 250, 251, 0.85)",
      "backdropFilter": "blur(10px)",
      "borderBottom": "1px solid var(--chakra-colors-line)",
    },
    ".nav__inner": {
      "display": "flex",
      "alignItems": "center",
      "justifyContent": "space-between",
      "height": "76px",
    },
    ".nav__logo": {
      "fontWeight": "800",
      "fontSize": "16px",
      "letterSpacing": "-0.01em",
    },
    ".nav__links": {
      "display": "flex",
      "alignItems": "center",
      "gap": "32px",
      "@media (max-width: 860px)": {
        "position": "absolute",
        "top": "76px",
        "left": "0",
        "right": "0",
        "background": "var(--chakra-colors-white)",
        "borderBottom": "1px solid var(--chakra-colors-line)",
        "flexDirection": "column",
        "alignItems": "flex-start",
        "padding": "16px 24px 24px",
        "gap": "18px",
        "display": "none",
      },
    },
    ".nav__link": {
      "fontSize": "15px",
      "fontWeight": "500",
      "color": "var(--chakra-colors-ink-soft)",
    },
    ".nav__link:hover": {
      "color": "var(--chakra-colors-ink)",
    },
    ".nav__cta": {
      "marginLeft": "8px",
      "@media (max-width: 860px)": {
        "marginLeft": "0",
      },
    },
    ".nav__toggle": {
      "display": "none",
      "flexDirection": "column",
      "gap": "5px",
      "background": "none",
      "border": "none",
      "cursor": "pointer",
      "padding": "8px",
      "@media (max-width: 860px)": {
        "display": "flex",
      },
    },
    ".nav__toggle span": {
      "width": "22px",
      "height": "2px",
      "background": "var(--chakra-colors-ink)",
      "display": "block",
    },
    ".hero": {
      "padding": "80px 0 100px",
    },
    ".hero__grid": {
      "display": "grid",
      "gridTemplateColumns": "1.1fr 0.9fr",
      "gap": "48px",
      "alignItems": "center",
      "@media (max-width: 900px)": {
        "gridTemplateColumns": "1fr",
      },
    },
    ".hero__art": {
      "position": "relative",
      "aspectRatio": "4 / 3",
      "borderRadius": "var(--radius-lg)",
      "background": "linear-gradient(160deg, var(--chakra-colors-mist), #ffffff)",
      "border": "1px solid var(--chakra-colors-line)",
      "overflow": "hidden",
      "display": "flex",
      "alignItems": "center",
      "justifyContent": "center",
    },
    ".hero__art .blob": {
      "position": "absolute",
      "borderRadius": "50%",
    },
    ".hero__art .blob--blue": {
      "width": "46%",
      "aspectRatio": "1",
      "background": "var(--chakra-colors-blue)",
      "left": "14%",
      "top": "28%",
    },
    ".hero__art .blob--maroon": {
      "width": "40%",
      "aspectRatio": "1",
      "background": "var(--chakra-colors-maroon)",
      "opacity": "0.9",
      "right": "12%",
      "top": "38%",
    },
    ".hero__art .chip": {
      "position": "absolute",
      "bottom": "24px",
      "right": "24px",
      "background": "var(--chakra-colors-ink)",
      "color": "var(--chakra-colors-white)",
      "fontSize": "12px",
      "fontWeight": "700",
      "letterSpacing": "0.08em",
      "padding": "8px 14px",
      "borderRadius": "999px",
    },
    ".statbar": {
      "display": "grid",
      "gridTemplateColumns": "repeat(4, 1fr)",
      "gap": "24px",
      "padding": "40px 0",
      "borderTop": "1px solid var(--chakra-colors-line)",
      "borderBottom": "1px solid var(--chakra-colors-line)",
      "@media (max-width: 700px)": {
        "gridTemplateColumns": "repeat(2, 1fr)",
      },
    },
    ".statbar__item .value": {
      "fontSize": "32px",
      "fontWeight": "800",
      "color": "var(--chakra-colors-blue)",
    },
    ".statbar__item .label": {
      "marginTop": "6px",
      "fontSize": "14px",
      "color": "var(--chakra-colors-ink-soft)",
    },
    ".props-grid": {
      "display": "grid",
      "gridTemplateColumns": "repeat(3, 1fr)",
      "gap": "24px",
      "marginTop": "48px",
      "@media (max-width: 860px)": {
        "gridTemplateColumns": "1fr",
      },
    },
    ".prop-card": {
      "padding": "32px",
      "border": "1px solid var(--chakra-colors-line)",
      "borderRadius": "var(--radius-md)",
      "background": "var(--chakra-colors-white)",
    },
    ".prop-card h3": {
      "marginBottom": "12px",
    },
    ".prop-card p": {
      "color": "var(--chakra-colors-ink-soft)",
      "lineHeight": "1.6",
      "fontSize": "15px",
    },
    ".section-head": {
      "display": "flex",
      "alignItems": "flex-end",
      "justifyContent": "space-between",
      "gap": "24px",
      "flexWrap": "wrap",
    },
    ".work-grid": {
      "display": "grid",
      "gridTemplateColumns": "repeat(3, 1fr)",
      "gap": "24px",
      "marginTop": "48px",
      "@media (max-width: 980px)": {
        "gridTemplateColumns": "repeat(2, 1fr)",
      },
      "@media (max-width: 640px)": {
        "gridTemplateColumns": "1fr",
      },
    },
    ".work-card": {
      "display": "block",
      "borderRadius": "var(--radius-md)",
      "overflow": "hidden",
      "border": "1px solid var(--chakra-colors-line)",
      "background": "var(--chakra-colors-white)",
      "boxShadow": "var(--shadow-card)",
      "transition": "transform 0.2s ease",
    },
    ".work-card:hover": {
      "transform": "translateY(-4px)",
    },
    ".work-card__cover": {
      "aspectRatio": "4 / 3",
      "display": "flex",
      "alignItems": "flex-end",
      "padding": "20px",
    },
    ".work-card__cover .tag": {
      "background": "rgba(255,255,255,0.85)",
      "color": "var(--chakra-colors-ink)",
      "fontSize": "12px",
      "fontWeight": "700",
      "padding": "6px 12px",
      "borderRadius": "999px",
    },
    ".work-card__body": {
      "padding": "22px",
    },
    ".work-card__body h3": {
      "marginBottom": "8px",
    },
    ".work-card__body p": {
      "color": "var(--chakra-colors-ink-soft)",
      "fontSize": "14px",
      "lineHeight": "1.5",
    },
    ".work-card__meta": {
      "marginTop": "14px",
      "display": "flex",
      "gap": "10px",
      "fontSize": "12px",
      "color": "var(--chakra-colors-ink-soft)",
      "textTransform": "uppercase",
      "letterSpacing": "0.06em",
    },
    ".testimonial": {
      "background": "var(--chakra-colors-ink)",
      "color": "var(--chakra-colors-white)",
      "borderRadius": "var(--radius-lg)",
      "padding": "64px",
      "textAlign": "center",
      "@media (max-width: 700px)": {
        "padding": "40px 24px",
      },
    },
    ".testimonial blockquote": {
      "fontSize": "clamp(22px, 3vw, 32px)",
      "fontWeight": "600",
      "lineHeight": "1.4",
      "maxWidth": "760px",
      "margin": "0 auto",
    },
    ".testimonial cite": {
      "display": "block",
      "marginTop": "24px",
      "fontStyle": "normal",
      "color": "rgba(255,255,255,0.6)",
      "fontSize": "14px",
    },
    ".footer": {
      "borderTop": "1px solid var(--chakra-colors-line)",
      "background": "var(--chakra-colors-white)",
      "paddingTop": "56px",
    },
    ".footer__inner": {
      "display": "grid",
      "gridTemplateColumns": "1.2fr 1fr 1fr",
      "gap": "32px",
      "paddingBottom": "40px",
      "@media (max-width: 720px)": {
        "gridTemplateColumns": "1fr",
      },
    },
    ".footer__wordmark": {
      "fontWeight": "800",
      "fontSize": "18px",
    },
    ".footer__role": {
      "color": "var(--chakra-colors-ink-soft)",
      "marginTop": "6px",
      "fontSize": "14px",
    },
    ".footer__links": {
      "display": "flex",
      "flexDirection": "column",
      "gap": "10px",
      "fontSize": "14px",
      "color": "var(--chakra-colors-ink-soft)",
    },
    ".footer__links a:hover": {
      "color": "var(--chakra-colors-ink)",
    },
    ".footer__contact": {
      "display": "flex",
      "flexDirection": "column",
      "gap": "8px",
      "fontSize": "14px",
      "color": "var(--chakra-colors-ink-soft)",
    },
    ".footer__socials": {
      "display": "flex",
      "gap": "14px",
      "marginTop": "4px",
    },
    ".footer__bottom": {
      "borderTop": "1px solid var(--chakra-colors-line)",
      "padding": "20px 24px",
      "fontSize": "13px",
      "color": "var(--chakra-colors-ink-soft)",
    },
    ".cs-hero": {
      "padding": "64px 0 32px",
    },
    ".cs-grid": {
      "display": "grid",
      "gridTemplateColumns": "repeat(2, 1fr)",
      "gap": "28px",
      "marginTop": "40px",
      "@media (max-width: 780px)": {
        "gridTemplateColumns": "1fr",
      },
    },
    ".cs-card": {
      "display": "block",
      "borderRadius": "var(--radius-lg)",
      "overflow": "hidden",
      "border": "1px solid var(--chakra-colors-line)",
      "background": "var(--chakra-colors-white)",
      "boxShadow": "var(--shadow-card)",
      "transition": "transform 0.2s ease",
    },
    ".cs-card:hover": {
      "transform": "translateY(-4px)",
    },
    ".cs-card__cover": {
      "aspectRatio": "16 / 10",
      "position": "relative",
      "display": "flex",
      "alignItems": "flex-start",
      "justifyContent": "space-between",
      "padding": "24px",
    },
    ".cs-card__cover .num": {
      "fontSize": "13px",
      "fontWeight": "700",
      "color": "rgba(255,255,255,0.85)",
    },
    ".cs-card__cover .name": {
      "fontSize": "30px",
      "fontWeight": "800",
      "color": "var(--chakra-colors-white)",
      "alignSelf": "flex-end",
    },
    ".cs-card__body": {
      "padding": "24px",
    },
    ".cs-card__body p": {
      "color": "var(--chakra-colors-ink-soft)",
      "fontSize": "14px",
      "marginTop": "8px",
      "lineHeight": "1.5",
    },
    ".cs-card__tags": {
      "display": "flex",
      "gap": "8px",
      "marginTop": "14px",
      "flexWrap": "wrap",
    },
    ".cs-card__tags span": {
      "fontSize": "12px",
      "padding": "5px 10px",
      "borderRadius": "999px",
      "background": "var(--chakra-colors-mist)",
      "color": "var(--chakra-colors-blue-dark)",
      "fontWeight": "600",
    },
    ".csd-header": {
      "padding": "56px 0 40px",
      "borderBottom": "1px solid var(--chakra-colors-line)",
    },
    ".csd-header .eyebrow": {
      "marginBottom": "20px",
    },
    ".csd-meta": {
      "display": "flex",
      "gap": "32px",
      "flexWrap": "wrap",
      "marginTop": "28px",
    },
    ".csd-meta div": {
      "fontSize": "14px",
    },
    ".csd-meta .label": {
      "color": "var(--chakra-colors-ink-soft)",
      "marginBottom": "4px",
      "textTransform": "uppercase",
      "letterSpacing": "0.06em",
      "fontSize": "12px",
    },
    ".csd-meta .value": {
      "fontWeight": "700",
    },
    ".csd-cover": {
      "marginTop": "40px",
      "aspectRatio": "21 / 9",
      "borderRadius": "var(--radius-lg)",
    },
    ".csd-stats": {
      "display": "grid",
      "gridTemplateColumns": "repeat(4, 1fr)",
      "gap": "20px",
      "padding": "40px 0",
      "borderBottom": "1px solid var(--chakra-colors-line)",
      "@media (max-width: 700px)": {
        "gridTemplateColumns": "repeat(2, 1fr)",
      },
    },
    ".csd-stats .value": {
      "fontSize": "28px",
      "fontWeight": "800",
    },
    ".csd-stats .label": {
      "fontSize": "13px",
      "color": "var(--chakra-colors-ink-soft)",
      "marginTop": "4px",
    },
    ".csd-block": {
      "padding": "72px 0",
      "borderBottom": "1px solid var(--chakra-colors-line)",
    },
    ".csd-block .kicker": {
      "fontSize": "13px",
      "fontWeight": "800",
      "color": "var(--chakra-colors-ink-soft)",
      "letterSpacing": "0.06em",
      "marginBottom": "14px",
    },
    ".csd-block h2": {
      "marginBottom": "20px",
    },
    ".csd-block .body-grid": {
      "display": "grid",
      "gridTemplateColumns": "1.2fr 0.8fr",
      "gap": "48px",
      "marginTop": "28px",
      "alignItems": "start",
      "@media (max-width: 860px)": {
        "gridTemplateColumns": "1fr",
      },
    },
    ".csd-block p.lead": {
      "fontSize": "17px",
      "lineHeight": "1.7",
      "color": "var(--chakra-colors-ink-soft)",
    },
    ".pull-quote": {
      "borderLeft": "3px solid var(--chakra-colors-blue)",
      "padding": "4px 0 4px 20px",
      "fontSize": "18px",
      "fontWeight": "600",
      "lineHeight": "1.5",
    },
    ".pull-quote cite": {
      "display": "block",
      "marginTop": "12px",
      "fontStyle": "normal",
      "fontSize": "13px",
      "fontWeight": "500",
      "color": "var(--chakra-colors-ink-soft)",
    },
    ".testimonial-grid": {
      "display": "grid",
      "gridTemplateColumns": "repeat(3, 1fr)",
      "gap": "32px",
      "marginTop": "28px",
      "@media (max-width: 860px)": {
        "gridTemplateColumns": "1fr",
      },
    },
    ".testimonial-grid .pull-quote": {
      "fontSize": "15px",
    },
    ".testimonial-title": {
      "display": "block",
      "fontWeight": "400",
      "marginTop": "2px",
    },
    ".swatch-row": {
      "display": "flex",
      "gap": "16px",
      "marginTop": "24px",
    },
    ".swatch": {
      "flex": "1",
      "borderRadius": "var(--radius-md)",
      "padding": "20px",
      "color": "var(--chakra-colors-white)",
      "minHeight": "96px",
      "display": "flex",
      "flexDirection": "column",
      "justifyContent": "flex-end",
    },
    ".swatch .name": {
      "fontWeight": "700",
      "fontSize": "14px",
    },
    ".swatch .hex": {
      "fontSize": "12px",
      "opacity": "0.85",
      "marginTop": "2px",
    },
    ".type-sample": {
      "padding": "20px",
      "border": "1px solid var(--chakra-colors-line)",
      "borderRadius": "var(--radius-md)",
    },
    ".type-sample .big": {
      "fontSize": "26px",
      "fontWeight": "700",
    },
    ".type-sample .small": {
      "marginTop": "6px",
      "fontSize": "13px",
      "color": "var(--chakra-colors-ink-soft)",
    },
    ".csd-implementation-image": {
      "display": "block",
      "width": "100%",
      "borderRadius": "var(--radius-lg)",
      "border": "1px solid var(--chakra-colors-line)",
      "marginTop": "28px",
    },
    ".steps": {
      "display": "grid",
      "gridTemplateColumns": "repeat(3, 1fr)",
      "gap": "24px",
      "marginTop": "32px",
      "@media (max-width: 860px)": {
        "gridTemplateColumns": "1fr",
      },
    },
    ".step": {
      "padding": "26px",
      "border": "1px solid var(--chakra-colors-line)",
      "borderRadius": "var(--radius-md)",
      "background": "var(--chakra-colors-white)",
    },
    ".step .index": {
      "fontSize": "12px",
      "fontWeight": "800",
      "color": "var(--chakra-colors-blue)",
      "marginBottom": "10px",
    },
    ".step h3": {
      "fontSize": "18px",
      "marginBottom": "8px",
    },
    ".step p": {
      "fontSize": "14px",
      "color": "var(--chakra-colors-ink-soft)",
      "lineHeight": "1.6",
    },
    ".more-resources": {
      "marginTop": "48px",
    },
    ".more-resources h3": {
      "fontSize": "16px",
      "marginBottom": "18px",
    },
    ".more-resources__grid": {
      "display": "grid",
      "gridTemplateColumns": "repeat(3, 1fr)",
      "gap": "20px",
      "@media (max-width: 860px)": {
        "gridTemplateColumns": "1fr",
      },
    },
    ".more-resources__card": {
      "display": "flex",
      "flexDirection": "column",
      "padding": "22px",
      "border": "1px solid var(--chakra-colors-line)",
      "borderRadius": "var(--radius-md)",
      "background": "var(--chakra-colors-white)",
      "transition": "border-color 0.2s ease, transform 0.2s ease",
    },
    ".more-resources__card:hover": {
      "borderColor": "var(--chakra-colors-blue)",
      "transform": "translateY(-2px)",
    },
    ".more-resources__label": {
      "fontSize": "15px",
      "fontWeight": "700",
    },
    ".more-resources__card p": {
      "fontSize": "13px",
      "color": "var(--chakra-colors-ink-soft)",
      "lineHeight": "1.6",
      "marginTop": "6px",
      "flex": "1",
    },
    ".more-resources__link": {
      "fontSize": "13px",
      "fontWeight": "700",
      "color": "var(--chakra-colors-blue)",
      "marginTop": "14px",
    },
    ".results-grid": {
      "display": "grid",
      "gridTemplateColumns": "repeat(4, 1fr)",
      "gap": "16px",
      "marginTop": "8px",
      "@media (max-width: 700px)": {
        "gridTemplateColumns": "repeat(2, 1fr)",
      },
    },
    ".results-grid .cell": {
      "padding": "22px",
      "borderRadius": "var(--radius-md)",
      "border": "1px solid var(--chakra-colors-line)",
    },
    ".results-grid .value": {
      "fontSize": "26px",
      "fontWeight": "800",
    },
    ".results-grid .label": {
      "fontSize": "13px",
      "color": "var(--chakra-colors-ink-soft)",
      "marginTop": "4px",
    },
    ".csd-cta": {
      "padding": "80px 0",
      "textAlign": "center",
    },
    ".csd-cta h2": {
      "marginBottom": "16px",
    },
    ".csd-cta .btn-row": {
      "justifyContent": "center",
    },
    ".csd-pager": {
      "display": "flex",
      "justifyContent": "space-between",
      "padding": "32px 0 80px",
      "fontSize": "14px",
      "fontWeight": "600",
    },
    ".csd-pager a:hover": {
      "color": "var(--chakra-colors-blue)",
    },
    ".about-hero": {
      "padding": "72px 0 24px",
    },
    ".about-hero .lede": {
      "maxWidth": "720px",
    },
    ".about-hero--grid": {
      "display": "grid",
      "gridTemplateColumns": "1.1fr 0.9fr",
      "gap": "48px",
      "alignItems": "center",
      "@media (max-width: 900px)": {
        "gridTemplateColumns": "1fr",
      },
    },
    ".portrait-frame": {
      "position": "relative",
      "width": "100%",
      "aspectRatio": "1 / 1",
      "maxWidth": "481px",
      "margin": "0 auto",
      "@media (max-width: 900px)": {
        "order": "-1",
        "marginBottom": "8px",
      },
    },
    ".portrait-frame__blob": {
      "position": "absolute",
      "borderRadius": "50%",
      "filter": "blur(64px)",
      "zIndex": "0",
    },
    ".portrait-frame__blob--blue": {
      "width": "40%",
      "aspectRatio": "1",
      "background": "var(--chakra-colors-mist)",
      "opacity": "0.5",
      "left": "-32px",
      "bottom": "-32px",
    },
    ".portrait-frame__blob--maroon": {
      "width": "53%",
      "aspectRatio": "1",
      "background": "var(--chakra-colors-maroon)",
      "opacity": "0.3",
      "right": "-32px",
      "top": "-32px",
    },
    ".portrait-frame__image": {
      "position": "relative",
      "zIndex": "2",
      "width": "100%",
      "height": "100%",
      "borderRadius": "var(--radius-md)",
      "overflow": "hidden",
      "boxShadow": "0 25px 50px -12px rgba(18, 19, 26, 0.25)",
      "background": "var(--chakra-colors-line)",
    },
    ".portrait-frame__image img": {
      "width": "100%",
      "height": "100%",
      "objectFit": "cover",
    },
    ".journey-grid": {
      "display": "grid",
      "gridTemplateColumns": "repeat(3, 1fr)",
      "gap": "24px",
      "marginTop": "40px",
      "@media (max-width: 780px)": {
        "gridTemplateColumns": "1fr",
      },
    },
    ".journey-grid .value": {
      "fontSize": "34px",
      "fontWeight": "800",
      "color": "var(--chakra-colors-blue)",
    },
    ".journey-grid .label": {
      "marginTop": "8px",
      "color": "var(--chakra-colors-ink-soft)",
      "fontSize": "14px",
    },
    ".skills-section": {
      "background": "var(--chakra-colors-ink)",
      "color": "var(--chakra-colors-white)",
    },
    ".skills-section .eyebrow": {
      "color": "#8FA0FF",
    },
    ".skills-grid": {
      "display": "grid",
      "gridTemplateColumns": "repeat(4, 1fr)",
      "gap": "20px",
      "marginTop": "40px",
      "@media (max-width: 980px)": {
        "gridTemplateColumns": "repeat(2, 1fr)",
      },
      "@media (max-width: 560px)": {
        "gridTemplateColumns": "1fr",
      },
    },
    ".skill-card": {
      "padding": "26px",
      "borderRadius": "var(--radius-md)",
      "background": "rgba(255,255,255,0.06)",
      "border": "1px solid rgba(255,255,255,0.12)",
    },
    ".skill-card h3": {
      "color": "var(--chakra-colors-white)",
      "marginBottom": "10px",
      "fontSize": "18px",
    },
    ".skill-card p": {
      "color": "rgba(255,255,255,0.65)",
      "fontSize": "14px",
      "lineHeight": "1.6",
    },
    ".contact-cta": {
      "textAlign": "center",
      "paddingTop": "96px",
    },
    ".contact-cta h2": {
      "maxWidth": "640px",
      "margin": "0 auto 16px",
    },
    ".contact-cta .lede": {
      "margin": "0 auto",
    },
    ".contact-cta .btn-row": {
      "justifyContent": "center",
    },
    ".notfound": {
      "padding": "160px 0",
      "textAlign": "center",
    },
    ".notfound .btn": {
      "marginTop": "28px",
    },
    ".mp-page": {
      "--font-body": "'Inter', sans-serif",
    },
    ".btn--mp-primary": {
      "background": "var(--chakra-colors-blue)",
      "color": "#fff",
    },
    ".btn--mp-primary:hover": {
      "background": "var(--chakra-colors-blue-dark)",
    },
    ".mp-hero": {
      "position": "relative",
      "padding": "140px 24px",
      "background": "linear-gradient(90deg, #ffffff 0%, #dde8f7 100%)",
      "display": "flex",
      "justifyContent": "flex-start",
      "overflow": "hidden",
    },
    ".mp-hero__portrait": {
      "position": "absolute",
      "right": "0",
      "bottom": "0",
      "maxWidth": "33%",
      "height": "auto",
      "pointerEvents": "none",
      "@media (max-width: 768px)": {
        "display": "none",
      },
    },
    ".mp-hero__inner": {
      "maxWidth": "min(1200px, 66%)",
      "width": "100%",
      "@media (max-width: 768px)": {
        "maxWidth": "100%",
      },
    },
    ".mp-hero__content": {
      "display": "flex",
      "flexDirection": "column",
      "gap": "24px",
    },
    ".mp-hero__eyebrow": {
      "color": "var(--chakra-colors-blue)",
      "marginBottom": "0",
    },
    ".mp-hero h1": {
      "fontSize": "clamp(38px, 6vw, 80px)",
      "fontWeight": "800",
      "lineHeight": "1.1",
      "letterSpacing": "-0.02em",
    },
    ".mp-hero__lede": {
      "fontFamily": "var(--font-body)",
      "color": "var(--chakra-colors-muted)",
      "fontSize": "20px",
      "lineHeight": "1.6",
      "maxWidth": "640px",
      "paddingTop": "8px",
    },
    ".mp-hero .btn-row": {
      "marginTop": "16px",
    },
    ".mp-values": {
      "padding": "120px 24px",
      "background": "#fff",
      "display": "flex",
      "justifyContent": "center",
    },
    ".mp-values__inner": {
      "maxWidth": "1200px",
      "width": "100%",
      "display": "flex",
      "flexDirection": "column",
      "gap": "64px",
    },
    ".mp-values__head": {
      "textAlign": "center",
      "display": "flex",
      "flexDirection": "column",
      "gap": "16px",
    },
    ".mp-values__eyebrow": {
      "color": "var(--chakra-colors-muted)",
      "marginBottom": "0",
    },
    ".mp-values__intro": {
      "fontFamily": "var(--font-body)",
      "color": "var(--chakra-colors-muted)",
      "fontSize": "18px",
      "lineHeight": "1.6",
      "maxWidth": "760px",
      "margin": "0 auto",
    },
    ".mp-values__grid": {
      "display": "flex",
      "flexWrap": "wrap",
      "justifyContent": "center",
      "gap": "32px",
    },
    ".mp-value-card": {
      "flex": "1 1 300px",
      "maxWidth": "380px",
      "padding": "40px 40px 56px",
      "background": "#F3F4F5",
      "backgroundImage": "radial-gradient(circle, rgba(0, 83, 219, 0.05) 0%, rgba(0, 83, 219, 0) 100%)",
      "border": "1px solid var(--chakra-colors-line)",
      "borderRadius": "var(--radius-md)",
      "display": "flex",
      "flexDirection": "column",
      "gap": "16px",
      "transition": "transform 0.3s ease, box-shadow 0.3s ease",
    },
    ".mp-value-card:hover": {
      "transform": "translateY(-8px)",
      "boxShadow": "0 20px 40px rgba(0, 0, 0, 0.05)",
    },
    ".mp-value-card__icon": {
      "width": "48px",
      "height": "48px",
      "borderRadius": "8px",
      "display": "flex",
      "alignItems": "center",
      "justifyContent": "center",
    },
    ".mp-value-card__icon img": {
      "width": "24px",
      "height": "24px",
    },
    ".mp-value-card h3": {
      "fontSize": "26px",
    },
    ".mp-value-card p": {
      "fontFamily": "var(--font-body)",
      "color": "var(--chakra-colors-muted)",
      "fontSize": "16px",
      "lineHeight": "1.5",
    },
    ".mp-deepdive": {
      "padding": "120px 24px",
      "background": "rgba(255, 251, 235, 0.4)",
      "display": "flex",
      "justifyContent": "center",
    },
    ".mp-deepdive__inner": {
      "maxWidth": "1200px",
      "width": "100%",
      "display": "flex",
      "flexWrap": "wrap",
      "gap": "64px",
      "alignItems": "center",
    },
    ".mp-deepdive__media": {
      "flex": "1 1 440px",
      "maxWidth": "568px",
    },
    ".mp-deepdive__media img": {
      "width": "100%",
      "height": "420px",
      "objectFit": "cover",
      "borderRadius": "var(--radius-md)",
      "boxShadow": "0 10px 40px -10px rgba(0, 0, 0, 0.15)",
    },
    ".mp-deepdive__content": {
      "flex": "1 1 440px",
      "maxWidth": "568px",
      "display": "flex",
      "flexDirection": "column",
      "gap": "16px",
    },
    ".mp-deepdive__eyebrow": {
      "color": "var(--chakra-colors-maroon)",
      "marginBottom": "0",
    },
    ".mp-deepdive__content p": {
      "fontFamily": "var(--font-body)",
      "color": "var(--chakra-colors-muted)",
      "fontSize": "18px",
      "lineHeight": "1.6",
    },
    ".mp-deepdive__tags": {
      "display": "flex",
      "flexWrap": "wrap",
      "gap": "12px",
      "paddingTop": "8px",
    },
    ".mp-deepdive__tags span": {
      "padding": "8px 16px",
      "background": "rgba(236, 253, 245, 1)",
      "borderRadius": "999px",
      "color": "rgba(125, 45, 0, 1)",
      "fontFamily": "var(--font-mono)",
      "fontSize": "12px",
    },
    ".mp-deepdive__link": {
      "display": "flex",
      "alignItems": "center",
      "gap": "12px",
      "paddingTop": "16px",
      "color": "var(--chakra-colors-blue)",
      "fontWeight": "700",
    },
    ".mp-deepdive__link:hover": {
      "textDecoration": "underline",
    },
    ".mp-work": {
      "padding": "120px 24px",
      "display": "flex",
      "justifyContent": "center",
    },
    ".mp-work__inner": {
      "maxWidth": "1200px",
      "width": "100%",
      "display": "flex",
      "flexDirection": "column",
      "gap": "64px",
    },
    ".mp-work__head": {
      "display": "flex",
      "justifyContent": "space-between",
      "alignItems": "flex-end",
      "flexWrap": "wrap",
      "gap": "24px",
    },
    ".mp-work__headcopy": {
      "display": "flex",
      "flexDirection": "column",
      "gap": "16px",
    },
    ".mp-work__eyebrow": {
      "color": "var(--chakra-colors-muted)",
      "marginBottom": "0",
    },
    ".mp-work__viewall": {
      "display": "flex",
      "alignItems": "center",
      "gap": "8px",
      "color": "var(--chakra-colors-muted)",
      "fontWeight": "700",
    },
    ".mp-work__viewall:hover": {
      "color": "var(--chakra-colors-ink)",
    },
    ".mp-work__grid": {
      "display": "grid",
      "gridTemplateColumns": "repeat(auto-fill, minmax(320px, 1fr))",
      "gap": "32px",
    },
    ".mp-work-card": {
      "display": "flex",
      "flexDirection": "column",
    },
    ".mp-work-card__cover": {
      "marginBottom": "24px",
      "borderRadius": "var(--radius-md)",
      "overflow": "hidden",
      "aspectRatio": "3 / 2",
      "display": "flex",
      "alignItems": "flex-end",
      "padding": "20px",
      "transition": "transform 0.3s ease, box-shadow 0.3s ease",
    },
    ".mp-work-card:hover .mp-work-card__cover": {
      "transform": "translateY(-8px)",
      "boxShadow": "0 20px 40px rgba(0, 0, 0, 0.05)",
    },
    ".mp-work-card__cover .tag": {
      "background": "rgba(255, 255, 255, 0.85)",
      "color": "var(--chakra-colors-ink)",
      "fontSize": "12px",
      "fontWeight": "700",
      "padding": "6px 12px",
      "borderRadius": "999px",
    },
    ".mp-work-card__category": {
      "color": "var(--chakra-colors-muted)",
      "marginBottom": "8px",
    },
    ".mp-work-card h3": {
      "fontSize": "26px",
      "marginBottom": "8px",
      "transition": "color 0.2s ease",
    },
    ".mp-work-card:hover .cs-title": {
      "color": "var(--chakra-colors-blue)",
    },
    ".mp-work-card p": {
      "fontFamily": "var(--font-body)",
      "color": "var(--chakra-colors-muted)",
      "fontSize": "16px",
      "lineHeight": "1.5",
    },
    ".mp-work-cta": {
      "background": "#111827",
      "borderRadius": "var(--radius-md)",
      "padding": "48px",
      "display": "flex",
      "flexDirection": "column",
      "justifyContent": "center",
      "minHeight": "380px",
      "transition": "transform 0.3s ease, box-shadow 0.3s ease",
    },
    ".mp-work-cta:hover": {
      "transform": "translateY(-8px)",
      "boxShadow": "0 20px 40px rgba(0, 0, 0, 0.05)",
    },
    ".mp-work-cta h3": {
      "color": "#fff",
      "fontSize": "clamp(28px, 3vw, 40px)",
      "fontWeight": "400",
      "lineHeight": "1.3",
      "marginBottom": "24px",
    },
    ".mp-work-cta p": {
      "fontFamily": "var(--font-body)",
      "color": "#C3C6D7",
      "fontSize": "18px",
      "lineHeight": "1.6",
      "marginBottom": "32px",
    },
    ".mp-work-cta a": {
      "color": "#B4C5FF",
      "fontWeight": "700",
      "display": "flex",
      "alignItems": "center",
      "gap": "12px",
    },
    ".mp-work-cta a:hover": {
      "textDecoration": "underline",
    },
    ".mp-motto": {
      "padding": "120px 24px",
      "background": "#F3F4F5",
      "display": "flex",
      "justifyContent": "center",
    },
    ".mp-motto__inner": {
      "maxWidth": "896px",
      "width": "100%",
      "display": "flex",
      "flexDirection": "column",
      "alignItems": "center",
      "gap": "32px",
      "textAlign": "center",
    },
    ".mp-motto__eyebrow": {
      "color": "var(--chakra-colors-muted)",
      "marginBottom": "0",
    },
    ".mp-motto blockquote": {
      "fontSize": "clamp(28px, 6vw, 64px)",
      "fontWeight": "800",
      "lineHeight": "1.15",
      "letterSpacing": "-0.02em",
    },
    ".mp-motto cite": {
      "fontFamily": "var(--font-mono)",
      "fontStyle": "normal",
      "fontSize": "14px",
      "fontWeight": "700",
      "letterSpacing": "1.4px",
    },
    ".nav__links--open": {
      "@media (max-width: 860px)": {
        "display": "flex",
      },
    },
    ".mp-hero, .mp-values, .mp-deepdive, .mp-work, .mp-motto": {
      "@media (max-width: 640px)": {
        "paddingLeft": "20px",
        "paddingRight": "20px",
      },
    },
  },
})

export const system = createSystem(defaultConfig, config)
